# Generated by Django 3.0.4 on 2020-03-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
