export const PET_OWNERS_FETCH_STARTED = 'PET_OWNERS_FETCH_STARTED';
export const PET_OWNERS_FETCH_COMPLETED = 'PET_OWNERS_FETCH_COMPLETED';
export const PET_OWNERS_FETCH_FAILED = 'PET_OWNERS_FETCH_FAILED';

export const PET_OWNER_ADD_STARTED = 'PET_OWNER_ADD_STARTED';
export const PET_OWNER_ADD_COMPLETED = 'PET_OWNER_ADD_COMPLETED';
export const PET_OWNER_ADD_FAILED = 'PET_OWNER_ADD_FAILED';

export const PET_OWNER_REMOVE_STARTED = 'PET_OWNER_REMOVE_STARTED';
export const PET_OWNER_REMOVE_COMPLETED = 'PET_OWNER_REMOVE_COMPLETED';
export const PET_OWNER_REMOVE_FAILED = 'PET_OWNER_REMOVE_FAILED';
